### PR TITLE
Fix styling issues in login with school page

### PR DESCRIPTION
**Pull request by edmgt**
### Description of change(s), including why:

This PR should fix the autoselect dropdown styling issues in login
with the school page. It also extracts that dropdown to a new SchoolPicker
component because it is used in (at least) 2 places

### Type of change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- (none)

### Closing issues:

- https://github.com/PollBuddy/PollBuddy/issues/280

### Screenshots (if frontend change) of before and after:

| Before             |  After |
:-------------------------:|:-------------------------:
image | image

### CODE REVIEW

**Review by hbh7 — DISMISSED** [review]
Looks great to me! Good idea with the component and thank you for contributing!

**Comment by hbh7** [comment]
Good data too as to how external PRs work with the workflows. I would have liked the lint ones to run but it's good for security that the CI one failed so we can ignore that here.

**Comment by hbh7** [comment]
A manual lint run has some simple concerns I'll fix at merge time, easiest that way I think.

**Comment by hbh7** [comment]
Nope just waiting on a 2nd review or for the review window to expire. All good on your end

**Review by annieshi6 — DISMISSED** [review]

**Pull request merged**
