### PR TITLE
Header dropdown menu

### LINKED ISSUE #174: Header dropdown menu
**Please describe what has to be done**
Create a dropdown menu in the header so that multiple pages are accessible both when the user is logged in and logged out.

**Additional context**
These are the following pages that we have so far, listed alphabetically, that should be displayed for each user. This list should be updated as we add more pages.

**Teacher, logged in:**
- accountinfo
- classcreation
- lesson/lessons
- myclasses
- pollDataView
- privacy
- settings

**Student, logged in:**
- accountinfo
- lesson/lessons
- myclasses
- pollDataView
- privacy
- settings

**Any user, logged out:**
- forgotpassword
- homepage/pollCode (These will be combined into the homepage)
- login
- privacy
- registerDefault
- registerWithPollBuddy
- registerWithSchool
- resetPassword

### PR DESCRIPTION
**Pull request by jssunray34**
### Description of change(s), including why:

I implemented a dropdown menu for the header. The dropdown menu will allow users to easily access different pages of the site from one central location. There are several menu items in the dropdown as requested: Login, Logout, Register, Account, Enter Poll Code, Groups, History, and Settings. Most of the menu items link to the appropriate pages.

All of these items are visible both when the user is logged in and logged out, but an issue should be made to make the menu dynamic and only show certain menu items when the user is logged in vs. logged out.

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- Make the following menu items visible only when the user is logged in: Logout, Account, Groups, History, and Settings.
- Make the following menu items visible only when the user is logged out: Login and Register.
- Make sure that each menu item links to the correct path (particularly History and Settings).

### Closing issues:

- Closes #174 

### Screenshots (if frontend change) of before and after:
PollBuddyBeforeHeaderDropdownMenu
PollBuddyHeaderDropdownMenu

### CODE REVIEW

**Review by hbh7 — CHANGES_REQUESTED** [review]
Looking good so far I'd say. Have you looked at https://github.com/PollBuddy/PollBuddy/issues/284? 

I think we're going to want a dedicated "Enter Poll Code" page probably, as well as some way to log out lol. 

Is it possible to make the dropdown collapse if you click outside it?

**Comment by jssunray34** [comment]
I added the functionality to make the dropdown collapse when you click outside of it.

The only problem is that when the user clicks outside of the menu to close it, and then clicks the menu button to open it again, it does not open. The user has to click the button once more to get it to open. I'm not sure why this is happening, but I've played with it a lot and cannot seem to get the functionality perfect.

**Review by annieshi6 — DISMISSED** [review]
for the most part, everything looks good!
I do want to fix up some of the css file and change the styling a bit though, if you don't mind
@hbh7 should a new issue be made for that or should i add it to this pr?

**Comment by hbh7** [comment]
Uhhh how major are the changes? It could be fine to just add on here. Got any ideas on the closing issue?

**Comment by annieshi6** [comment]
Nothing to add to the issue just changes to the css file / how it’s currently styled (e.g. some classes not necessary, dropdown positioning, clearer indication on hover, etc)

**Comment by hbh7** [comment]
Ok, sure if you'd like

**Comment by jssunray34** [comment]
Of course, I'm perfectly fine with changes to the styling.

**Comment by annieshi6** [comment]
That should be it for the styling and I also managed to figure out the 'having to click twice' problem
lmk if you have anything else in mind w the styling or if something's weird w the js file (I still don't actually know how to properly React lol)

**Review by hbh7 — APPROVED** [review]
Love it! 

And yeah I bet even the React developers don't know how to properly React lol

**Comment by jssunray34** [comment]
Awesome! Looks great

**Pull request merged**
