### PR TITLE
Polls rework

### LINKED ISSUE #414: Backend /api/polls/:id/new Endpoint Documentation
**Please describe what has to be done**
Document in both code and wiki what this route accepts, returns, and generally does.

**Additional context**
See #392.

### PR DESCRIPTION
**Pull request by Isaac-the-Man**
### Description of change(s), including why:

Reworked `POST /api/polls/new`, `POST /api/polls/:id/edit`, `GET /api/polls/`, and `GET /api/polls/:id` to make sure it works and followed the specifications we agreed on. Also fixed `validateID()` to make sure the supplied id exists the in database and some [documentations](https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Backend-Routes-(Polls))

### Type of change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- Many routes should be permission guarded.

### Closing issues:

- Closes #414, #387, #362, #361, #360, #359, #352, #353, #354

### CODE REVIEW

**Review by hbh7 — CHANGES_REQUESTED** [review]
Looking good so far. Can you create the JSDoc for these functions though? That way it's clear what's going on and how the frontend can use these.

**Review by hbh7 — CHANGES_REQUESTED** [review]
Are you still handling deleting questions in /:id/edit? I'm not sure I see a way to anymore. Also, can you document the error responses too. I think it's mostly just the "An error occurred while writing the database." message, but there could be more in the other functions edited. Also can you add a "to" between "writing" and "the". 

As for getting /api/polls/, I think this will later either get "removed" and return essentially nothing, or possibly just return all polls the user has access to. Otherwise, it's somewhat of a data leak. 

Finally, the /:id one I think is fine for now, but we'll eventually want a permissions check on it. 

Otherwise things are looking good!

**Comment by Isaac-the-Man** [comment]
> Are you still handling deleting questions in /:id/edit? I'm not sure I see a way to anymore. Also, can you document the error responses too. I think it's mostly just the "An error occurred while writing the database." message, but there could be more in the other functions edited. Also can you add a "to" between "writing" and "the".
> 
> As for getting /api/polls/, I think this will later either get "removed" and return essentially nothing, or possibly just return all polls the user has access to. Otherwise, it's somewhat of a data leak.
> 
> Finally, the /:id one I think is fine for now, but we'll eventually want a permissions check on it.
> 
> Otherwise things are looking good!

Deleting Questions can be done by (let say we originally have `[Q1, Q2, Q3]` and want to delete `Q2`) sending `[Q1, Q3]` back to the endpoint `/api/polls/:id/edit`. To delete all questions just send a empty array `[]` (I will put this example in the documentation)  .

**Comment by Isaac-the-Man** [comment]
I've added more explanations on the [wiki](https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Backend-Routes-(Polls)#post-idedit) for the `/edit` route.

**Review by hbh7 — APPROVED** [review]
I noticed some weird behavior occur where if I just went to /api/polls/new, it would give me an "Invalid ID" error. Looks like this is actually caused by the lack of a GET route and it falling through to /api/polls/:id. Guess that's another case for having GET and POST defined for everything. I suppose we can worry about it later but it's interesting nonetheless. 

Otherwise though, given that we don't have any sort of testing system, let alone a comprehensive one, I think everything looks good as far as I can tell! I expect things will continue to get more complex so I'm hoping to start a testing system this summer.

**Pull request merged**
