### PR TITLE
Total Responses Display

### LINKED ISSUE #653: Show total number of responses to polls
**Please describe what has to be done**
Add a total responses counter to the results page of polls. May need a backend endpoint

### PR DESCRIPTION
**Pull request by JMozes16**
### Description of change(s), including why:

Added the number of total responses to the bottom of the results page.

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- (none)

### Closing issues:

- Closes #653

### Screenshots (if frontend change) of before and after:

Before:
totalResponsesBefore

After:
TotalResponses_done

### CODE REVIEW

**Comment by JMozes16** [comment]
Did not realize "#1" would link haha.

**Review by hbh7 — CHANGES_REQUESTED** [review]
Not sure if this was ever specified or not but the total should represent how many unique users submitted, rather than how many of each response were tallied. Looks like it's a total of every response currently rather than per user. 
image

**Review by JaBeast13 — APPROVED** [review]
Looks good

**Review by hbh7 — APPROVED** [review]
Looks good!

**Pull request merged**
