### PR TITLE
Popup UI

### PR DESCRIPTION
**Pull request by pathfold**
### Description of change(s), including why:

I wrapped up this dynamic modal UI component that takes in two props: a dimming option and some text. The text is rendered and sits in the middle of the modal and the dimming boolean determines whether or not the modal overlay is visible/invisible. Additionally, it determines whether or not the component is a block-positioned or fixed-positioned component. Some needed additions to get this to work would be to add a handleClick/handleClose function that should probably be passed as a callback function into this Popup2 component from a parent component that will allow users to close this modal.

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- Add handling functions onClick of close button

### Closing issues:

- Progress on #419 

### Screenshots (if frontend change) of before and after:

Modal version
Screenshot_5

Block version
Screenshot_6

### CODE REVIEW

**Comment by hbh7** [comment]
I gave you a hand on formatting, looked like you were having a rough time lol

**Comment by pathfold** [comment]
Thanks Hunter!

**Comment by ashwinc12** [comment]
resolved merge conflicts

**Comment by hbh7** [comment]
> Live version has been created! Always-Updated URL: https://dev-511.pollbuddy.app/
> 
> Start Time: 2021/10/05 04:24:21 PM ET End Time: 2021/10/05 04:35:57 PM ET Last commit: [4de4790](https://github.com/PollBuddy/PollBuddy/commit/4de4790f19ef1c11d4fc00ee6f96eb40c033aeeb) Up-To-Commit URL: https://dev-4de4790f19ef1c11d4fc00ee6f96eb40c033aeeb.pollbuddy.app/

Wow that was a very late build for some reason... ¯\\\_(ツ)_/¯

**Pull request merged**
