### PR TITLE
use express-session to store logged in state

### PR DESCRIPTION
**Pull request by aidan-lane**
### Description of change(s), including why:

Moved user cookie system to backend using express session. Stores login state, email and password.

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- Maybe add username field too?

### Closing issues:

- N/A

### CODE REVIEW

**Review by hbh7 — CHANGES_REQUESTED** [review]
A couple things here:

- Request for comments on redirecting the homepage to the groups page if you're logged in. I'm not sure if we want that or not. 
- We definitely do not want to be storing user's passwords in the session. That's a security risk for a couple of reasons. Session isn't encrypted in the backend so we'd have plaintext passwords in the database. We'd also have plaintext passwords in the cookies on the client, which can be pretty easily read by some web attacks and even just regular PC-based attacks. 
- Take a look here at what we decided on for storing in the session: https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Frontend-Stored-Data
- Email isn't on that list but I have no issue adding it if we want. 

Otherwise though I think that you're certainly on the right track and almost there. I especially like the redirect to login functionality you essentially added as well by chance (it'd be identical to your redirect to /groups but with /login instead). 

P.S. Is this state going to exist across all pages?

**Comment by aidan-lane** [comment]
Made the changes you suggested, logged in state data is stored in localStorage so it can be accessed across all components. Also removed password from session and added added the other fields.

**Review by aidan-lane — COMMENTED** [review]
Fixed issues

**Review by hbh7 — APPROVED** [review]
Looks good now. I made a few small changes like lint fixes and moving /api/session to /api/users/session and made an issue for documentation (#390, would be great if you could do that too if you want).

Fast merging due to time constraints.

**Pull request merged**
