### PR TITLE
Update AccountInfo.js

### LINKED ISSUE #311: Register form details
**Please describe what has to be done**
Need to figure out what we want on the registration. I think we want Firstname, Lastname, Email, Password, at least. Currently we have Name but backend stores Firstname, Lastname and I believe we decided we liked that better so we'll want to split it at register too.

### PR DESCRIPTION
**Pull request by mkhodak2**
### Description of change(s), including why:

Changed name in the file to first name and last name 

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- (none)

### Closing issues:

- Closes #311

### CODE REVIEW

**Review by hbh7 — CHANGES_REQUESTED** [review]
It would be great if you could add an [non-editable](https://www.w3schools.com/tags/att_input_readonly.asp) box for username too. Thanks

**Review by hbh7 — APPROVED** [review]
Whacky react made it readOnly, not readonly, so I changed that. Otherwise looks good. We'll want to make these prepopulated instead of using placeholders eventually but that's already in the issue and can be done elsewhere.

**Review by annieshi6 — CHANGES_REQUESTED** [review]
Looks good! But I feel like fields that we're going to prepopulate (prob all except password stuff) would be better with values instead of placeholders so that information doesn't just disappear onfocus

**Comment by mkhodak2** [comment]
> Looks good! But I feel like fields that we're going to prepopulate (prob all except password stuff) would be better with values instead of placeholders so that information doesn't just disappear onfocus

Thanks for reviewing my PR! What exactly does values mean in terms of placeholders, could you maybe give an example? Thanks!

**Comment by hbh7** [comment]
I agree they should change from placeholders to values, but I think that can happen elsewhere as the mechanism for populating them with real data isn't set up yet anyways. I think it's ok for now and will be fixed soon enough elsewhere.

**Review by annieshi6 — APPROVED** [review]

**Comment by annieshi6** [comment]
> What exactly does values mean in terms of placeholders, could you maybe give an example? Thanks!
As @hbh7 said it's not necessary rn but to answer ur question it would just be replacing the 'placeholder' property w 'value'. The placeholder property is really just for looks vs value which is actual data u can edit.

**Comment by annieshi6** [comment]
@hbh7 the readonly note adds another thing to my list of things to do: style readonly inputs so they're distinguishable!

**Comment by hbh7** [comment]
@annieshi6 sounds good, I was thinking the same thing. I'll open an issue for you :)

**Pull request merged**
