### PR TITLE
Dev Mode Check

### LINKED ISSUE #571: Dev mode check function
**Please describe what has to be done**
Create a function to check if the app is running in development mode. Put it in the utils.js module and have it return true if the app is running in dev mode (check the DEV_MODE environment variable), or false if not. Check the routes files for similar checks and replace them with this new function. 
Also, upon completion, create an issue to add this check to the development routes

### PR DESCRIPTION
**Pull request by ashwinc12**
### Description of change(s), including why:

Added dev mode environment variable check

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- Create new issue to add this check to development routes.

### Closing issues:

- Closes #571

### CODE REVIEW

**Comment by ashwinc12** [comment]
Does this environment variable exist currently? I could not find it in the current .env file

**Comment by hbh7** [comment]
> Does this environment variable exist currently? I could not find it in the current .env file @hbh7

Take a look here: https://github.com/PollBuddy/PollBuddy/pull/581/files

It's defined in the Docker setup, so that it's automatic, but it should be fine to set it in the .env file too.

**Comment by ashwinc12** [comment]
@hbh7  Lmk if any other changes are needed 👍

**Review by hbh7 — APPROVED** [review]
Looks good! I swapped the env example part to be commented out by default as it should be set by Docker anyways, and therefore a default off would be better since the prod one would also then run in dev mode if told to by the env file, which could be confusing unless you know what you're doing.

**Pull request merged**
