### PR TITLE
Question update

### LINKED ISSUE #158: Update Question Component
**Please describe what has to be done**
The question component doesn't fit the PollBuddy's theme style-wise. The timer feature is also broken.
- [x] update styling
- [x] fix timer

### PR DESCRIPTION
**Pull request by nbezanis**
### Description of change(s), including why:

Updated the question component to use pollbuddy's new style guides and fixed the timer.

### Type of change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- The width of the bubbles that contain the answer choices (A, B, C, ect) fits the text inside but I don't know how to make the height always match the width 
- Here is the json structure that the question component accepts
```
{
  "questionNumber": "3",
  "question": "Why does the tooth fairy collect teeth?",
  "img": "https://i.kym-cdn.com/photos/images/newsfeed/001/409/553/5f5.png",
  "choices": [
    "She grinds them into the fairy dust she needs to fly",
    "She gives them to new babies who are ready to grow teeth",
    "She gives the good teeth to dentists to make false teeth",
    "She grinds them up and makes sand for the beach",
    "She needs to replace her own teeth",
  ],
  "points": 2,
  "maxAllowedChoices": 2,
  "timeLimit": 10
}
```

### Closing issues:

- Closes #158 

### Screenshots (if frontend change) of before and after:

Here's how the component looks
question

You can also include a picture
questionPic

The answer choices are auto generated and will continue past Z
questionChoices

### CODE REVIEW

**Comment by neha-deshpande001** [comment]
Looks like the eslint checks didn't pass, so we can't see the live version yet

**Review by neha-deshpande001 — APPROVED** [review]
Looks good! I just made a commit to make the buttons circles. It looks fine for one and two-character labels, but not more than that. This should be fine, right? We're not expecting any questions to have more than 48 answer choices...

circle buttons
circles2

**Comment by hbh7** [comment]
Related discussion: https://github.com/PollBuddy/PollBuddy/issues/385
(Does not need to be settled/implemented before this PR merges)

**Review by hbh7 — APPROVED** [review]
Awesome! I thought it was very interesting the way you did the label generation. I probably would have done it with ascii values and a loop rather than the array but that's really essentially the same thing. Very neat to get the perspective though and I do like your method.

**Comment by hbh7** [comment]
Also as for over 48 answer choices, I think that's very unlikely but I will be curious to query the database in a few months or years and see if anyone's done it lol. At that point, we can consider worrying about the styling in that case.

**Comment by hbh7** [comment]
There was a lot of merge conflicts involved so it's possible something went wrong somewhere. Please let me know if anyone finds anything. Thanks

**Pull request merged**
