### PR TITLE
Poll code component

### LINKED ISSUE #312: Enter poll code page
**Please describe what has to be done**
Since it's an option in the header, we'll want a dedicated page for it after all. I think we can get away with just making the poll code box on the homepage a separate component, and then making a page with just that on it so we have the same thing in both places. 

**Additional context**
Change the header link to point to the poll code page too. I think we'll want to make the url /pollcode or /code or something like that.

### PR DESCRIPTION
**Pull request by neha-deshpande001**
### Description of change(s), including why:

Created a component for the "enter poll code" box which looks exactly the same and has the same functionality, which I then added onto the homepage. Then, I created a new page and added the PollCode component onto that page.

### Type of change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- add a link from the header dropdown to the /code page

### Closing issues:

- Closes #312 

### Screenshots (if frontend change) of before and after:
Homepage looks the same
image

Here's the code page
image

### CODE REVIEW

**Review by hbh7 — CHANGES_REQUESTED** [review]
Tiny thing, can you move the /code route to below the /privacy route so grouping is preserved? ~~Labeling the sections would be nice too if you don't mind. Just something simple like `{ \* Main site pages *\ }`, `{ \* Group pages *\ }`, etc.~~ (Nevermind, that really should be its own issue)

**Comment by neha-deshpande001** [comment]
Done!

**Review by hbh7 — APPROVED** [review]
Great, thanks!

**Review by annieshi6 — APPROVED** [review]

**Review by annieshi6 — APPROVED** [review]
sorry, just a tiny change that i didn't want to make a whole branch for !

**Review by hbh7 — APPROVED** [review]

**Pull request merged**
