### PR TITLE
Privacy page loads text from markdown file

### LINKED ISSUE #188: Privacy page markdown/google doc
**Please describe what has to be done**
Look into incorporating a markdown/google doc onto the privacy page rather than typing directly on the page. It's much easier to update and maintain.

### PR DESCRIPTION
**Pull request by emanua**
### Description of change(s), including why:

Updated the privacy policy page to display its text from a markdown file. This makes it easier to update and maintain the page, without having to modify the code / HTML. Visually everything is displayed exactly the same, except links are now clickable.

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- Privacy policy itself still needs to be written

### Closing issues:

- Closes #188

### CODE REVIEW

**Comment by hbh7** [comment]
Very neat, looks good at first glance but I'll play around with it tonight to be sure, and then merge if someone else has approved too. 

Something also about assigning, I know it's weird and confusing so I just wanted to clear up how we usually use them. All features (milestones, assignee's, reviewers, etc.) exist on both issues and pull requests, but we only use some for each. For issues, we use milestones and assignee's, but for PRs we use milestones and reviewers. 

Definitely no worries though, it's not a big deal or anything, nor does it really matter all that much, but just sharing so you know a bit more clearly where each tends to get used.

**Comment by emanua** [comment]
> Very neat, looks good at first glance but I'll play around with it tonight to be sure, and then merge if someone else has approved too.
> 
> Something also about assigning, I know it's weird and confusing so I just wanted to clear up how we usually use them. All features (milestones, assignee's, reviewers, etc.) exist on both issues and pull requests, but we only use some for each. For issues, we use milestones and assignee's, but for PRs we use milestones and reviewers.
> 
> Definitely no worries though, it's not a big deal or anything, nor does it really matter all that much, but just sharing so you know a bit more clearly where each tends to get used.

That makes sense, my bad!

**Comment by emanua** [comment]
> If we make any formatting changes on the privacy.md file, it doesn't show up on the page. For example, I added bullet points on privacy.md but it just looks like plain text on the privacy page. (it just be my machine, though?)

Thanks for reviewing and noticing this! I added proper bullet points with a simple addition in styling. A couple other features are still unstyled such as tables. I'm not sure why it does this yet, and it would be nice to have working, but unless I or someone else figures it out after investigating, we probably won't need to include tables, code, etc. for the pages using markdown?

**Comment by hbh7** [comment]
You're probably right about that. I think we can fix it on an as-needed basis (AKA later when it becomes a problem) rather than worrying about it right now.

**Pull request merged**
