### PR TITLE
Tech readme

### LINKED ISSUE #427: Frontend/backend tech list
**Please describe what has to be done**

- [x] Make a readme in the backend and frontend folders with a list of the tech used and a brief blurb of what it is, why it's used, and how it's used. 
- [x] Do the same on the main readme, but just list the tech, no explanations, so that it's brief. Maybe make a note to see the individual readmes for more info.

### PR DESCRIPTION
**Pull request by EthanTuttle**
### Description of change(s), including why:

Created 2 readmes, one on the front-end and one on the back-end that list the technologies we use, a blurb about what they are, and a small example of the way we use it for the more complicated ones. I also linked these on the main readme and included a small list with it

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- (none)

### Closing issues:

- Closes #427

### CODE REVIEW

**Comment by EthanTuttle** [comment]
Let me know if this was what you wanted from #427 Hunter

**Review by hbh7 — CHANGES_REQUESTED** [review]
Your markdown is a little bit rough, but all the content is great! If you could just reformat it a bit, that'd be great. 

As an example: 
```
## connect-mongo
-Package for linking Express session to a mongoDB session

NPM Link: https://www.npmjs.com/package/connect-mongo



# <next one>
```

Can become: 
```
## connect-mongo
Package for linking Express session to a mongoDB session

NPM Link: https://www.npmjs.com/package/connect-mongo


# <next one> 
```

It's mainly just the leading dash that looks weird, and 2 newlines of spacing between modules is plenty. Nothing major :)

**Comment by EthanTuttle** [comment]
Okay it should be good now

**Review by hbh7 — APPROVED** [review]
Looks good! I did some editing to clean things up a bit more, and update a few things.

**Pull request merged**
