### PR TITLE
Improved accessibility

### LINKED ISSUE #199: Do we need labels above all text inputs for accessibility?
Some pages have a label, some don't.
Some pages have a placeholder, some don't.
Should we use emojis for placeholders/labels?

Figure this out and make it unified for each page

### PR DESCRIPTION
**Pull request by walkingjason**
Added aria-label in multiple input boxes
Changed login button text color

WAVE evaluates no errors

### Description of change(s), including why:

According to WAVE evaluation tool, we have labelling errors and contrast errors.
Added aria-label in multiple input boxes
Changed login button text color

### Type of change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- Further evaluation needs to be made if we wish to implement a dark/light mode switch

### Closing issues:

- Closes #199 #37 

### Screenshots (if frontend change) of before and after:

before
after

### CODE REVIEW

**Comment by annieshi6** [comment]
Also, does use of aria-label mean labels above input fields are no longer necessary? I'm not exactly sure how it works but it just seems repetitive for a screen reader.
If we choose to keep the text labels maybe use aria-labelledby on the input fields instead, so if we choose to change a label it'll change for both. (Just reduces the risk of changing one and forgetting about the other)

**Comment by hbh7** [comment]
Based off of https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA, 
my understanding is that ARIA Labels are used when a traditional label can't be used for some reason. They also seem to be mostly deprecated in favor of modern HTML5 alternatives, so I would personally try to avoid them as much as possible. 

Do you have/can you make a list of locations where traditional labels wouldn't make sense?

**Comment by hbh7** [comment]
Look good. Just want to clarify though, have you gone through all the pages or only some? In other words, is this done and ready for review?

**Comment by hbh7** [comment]
(Notes from 07/24/2020 meeting)
Yes, ready to be reviewed

**Comment by hbh7** [comment]
@annieshi6 good catch!

**Pull request merged**
