### PR TITLE
Registration client side validation

### LINKED ISSUE #308: Registration server-side validation update for new rules
**Please describe what has to be done**
Ensure that user registration details are validated prior to creating the user in the backend. Also send back an array of error messages if criteria isn't met. It'd be nice if they matched/were very similar to the ones on the frontend. See #307

- [x] First name validation
- [x] Last name validation
- [x] User name validation
- [x] Email validation
- [x] Password validation

**Additional context**
See https://github.com/PollBuddy/PollBuddy/issues/298 and https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-User-Data

### PR DESCRIPTION
**Pull request by lulujoe**
### Description of change(s), including why:

The key change is that for backend api (user/register), it has three return values right now:
1. an error dictionary: {firstname: "Invalid firstname format!", lastname: "Invalid lastname format!"}
2. a string: Exists, which means the email address has already been registered
3. status 203: everything is ok

The last two are already existed and I add error dictionary as a new return value according to this request. 

I also modified the frontend so that it can figure out what it supposed to do based on the return values. If it accepts an error dictionary, currently I just use console.log to print it. It you need more actions, I can do that. 

According to my understanding, since we do the same checks in frontend and backend, a normal client will never get the backend error messages. However, if a person intend to cause some damages, they can send the API request directly(ex. by postman), so it is necessary to add some checks in the backend. But, in this case, I don't think we need to add some fancy warning messages for our clients, so I just do console.log right now.

You can see more details and screenshoots below.

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- (none)

### Closing issues:

- Closes #308 

### Screenshots (if frontend change) of before and after:

When I did the tests, I stopped the firstname check in frontend and keep the rest of checks(lastname, username, email, password) because we cannot do the test since the frontend and backend have the same checks and all errors will stopped by frontend before sending requests to backend API. 

ps. yes, we can use postman to do that, but just for convenience 😄 .

test1: wrong firstname, wrong username, existed email
Screen Shot 2020-12-08 at 2 18 38 PM
result1: no backend call, frontend find some errors before send request to backend API.

test2: wrong firstname, existed email
Screen Shot 2020-12-08 at 2 19 03 PM
result2: backend finds the firstname error, returns an error array {firstname: "Invalid firstname format!"} and frontend console.log the error array

test3: existed email error only
Screen Shot 2020-12-08 at 2 19 24 PM
result3: no error array returned, instead the backend returns "existed" error message. So frontend shows red warnings and tells our client this email address has already been used.

test4: all correct
Screen Shot 2020-12-08 at 2 19 51 PM
result4: direct to the /groups page

### CODE REVIEW

**Comment by hbh7** [comment]
Hi, this seems to be a duplicate of #399 (the branch is the same). Was that intentional? Am I missing something? Thanks

**Comment by lulujoe** [comment]
Sorry, I finish task 307 first and pull the request 399 but I think I need to use the same approach to solve task 308.So I modified within the same branch. I am pretty sure current one is a final one that solve both task 307 and 308.

**Comment by hbh7** [comment]
Ok, I'll close the other PR and we'll just use this one then. 

Information from the other one (#399) for reference: 

### Description of change(s), including why:

Updated the validation based on new rules:
1. add first name validation: Minimum 1 character, maximum 256 characters.
2. add last name validation: Minimum 0 characters (can be left blank if not needed), maximum 256 characters.
3. password validation updated: use the suggested regex: ^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$
4. warning messages (firstname, lastname, username) updated and didn't change the original logic (bad input returns an error and not a crash ).

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- (none)

### Closing issues:

- Closes #307 

### Other Notes:

Aidan also reviewed and approved that one recently.

**Comment by hbh7** [comment]
Will merge into frontend since that was the original/primary focus

**Review by hbh7 — APPROVED** [review]
Looks good!

**Pull request merged**
