### PR TITLE
login-register buttons

### LINKED ISSUE #582: Don't show "login" and "register" buttons on the homepage if user is logged in
**Please describe what has to be done**
The "login" and "register" buttons don't make any sense to show to a user once they're logged in, so these buttons should be hidden from the homepage if a user is logged in.

### PR DESCRIPTION
**Pull request by JMozes16**
login/register button

### Description of change(s), including why:

When logged in, this will make the login and register buttons disappear. They will come back if user logs out.

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- (none)

### Closing issues:

- Closes #582

### Screenshots (if frontend change) of before and after:
Logged in or logged out before:
login_reg_before

Logged in after:
new_buttons

Logged out after:
login_reg_before

### CODE REVIEW

**Review by hbh7 — CHANGES_REQUESTED** [review]
I think this looks perfectly done, but now I'm feeling like it might be a bit empty. Perhaps if logged in, we show a button labeled "Go to My Groups" or something like that, and link to the groups page? Thoughts?

**Comment by JMozes16** [comment]
> I think this looks perfectly done, but now I'm feeling like it might be a bit empty. Perhaps if logged in, we show a button labeled "Go to My Groups" or something like that, and link to the groups page? Thoughts?

Just added My Account , and My Groups to the space to fill the space.

**Review by PrinxeShamar — DISMISSED** [review]

**Review by hbh7 — APPROVED** [review]
I swapped the merge-into branch to frontend is all, but otherwise this looks perfect. An if/else could have been used here, but that doesn't matter particularly much.

**Review by PrinxeShamar — APPROVED** [review]

**Comment by JMozes16** [comment]
Ready to be merged.

**Pull request merged**
