### PR TITLE
Added /api/schools request

### LINKED ISSUE #300: Backend call providing list of schools to sign in with
**Please describe what has to be done**
Probably under /api/schools perhaps. The argument could be made that it's part of users and should be /api/users/schools so that'd be fine too. Basically just return a json array of school names. When the user submits the login/register/etc request, we'd just include the school name (which should be unique) so the backend can then redirect the user to the right sign in URL. 

**Additional context**
May not have a place in the database schema doc, should look into that too.

### PR DESCRIPTION
**Pull request by Shadowsoftime99**
### Description of change(s), including why:
Added a (currently hard-coded) array of possible schools into the backend for access by future API calls. At the moment the schools were hard-coded into the frontend, which is worse practice and less easily expandable in the future.

### Type of change(s)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Closing issues:

- Closes #300

### CODE REVIEW

**Review by hbh7 — CHANGES_REQUESTED** [review]
Any luck with a "global" schools list and adding the schools individually per module like we were talking about before? 

Ex: SchoolLoginProviders Array in app.js, cas.js appends RPI's entry to that list, route reads that list.

While I'm thinking about it, it probably makes sense to rename cas.js to RPI.js so each school gets its own file. It's not at all unlikely that another school uses CAS too but that adds poor portability to put them both in the same module. Better to have 1 module per school IMO.

**Comment by Shadowsoftime99** [comment]
Er, sorry, I may not be understanding this correctly, but isn't the global list of schools what is implemented here? Unless the proposition is to have a list object that starts out empty, then gets passed to each cas (or equivalent) which populates it one by one? That seems... Extremely inefficient. Let me know, or we can talk on Friday or in Discord about the specifications on this.

**Review by hbh7 — APPROVED** [review]
Great! We may want to call it "Rensselaer Polytechnic Institute (RPI)" but that's pretty minor and unimportant. 

I think we can also avoid having the URL in the list, as the backend could route to the right place depending on what school name it gets sent, so this format should work good.

**Review by hbh7 — DISMISSED** [review]
Ok looks great now. I fixed up a few things like ESLint warnings and a few things that weren't renamed. I also tested and it seems to work great so :D

Since this is over the holidays, I may merge it tomorrow since it's been around a while and we're getting close to testing day. Hopefully someone else takes a gander before then though.

**Review by hbh7 — APPROVED** [review]
Darnit there goes my last review again lol

**Pull request merged**
