### PR TITLE
Group creation functionality

### LINKED ISSUE #273: Group Creation page functionality
**Please describe what has to be done**

- [ ] Should submit a request to the backend to handle this
- [ ] May or may not need additional fields, will need to be looked into
- [ ] Bounce to /login if user is not logged in

### PR DESCRIPTION
**Pull request by nbezanis**
### Description of change(s), including why:

Cleaned up backend functionality with the group creation/editor component. It now redirects to the group/pollid/polls page when you create a new group. Added code to hide the loading wheel when necessary. Made a new error text component and showed it when the backend returns an error.

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- Need backend functionality for checking if a user is logged in and we need some way to add polls and users/instructors

### Closing issues:

- Closes #273 

### Screenshots (if frontend change) of before and after:
error

### CODE REVIEW

**Review by hbh7 — CHANGES_REQUESTED** [review]
Looking good so far, just a few things: 

- [x] A couple lint fixes
- [x] We were talking about reworking GroupEditor/GroupCreation a bit over here https://github.com/PollBuddy/PollBuddy/pull/292#pullrequestreview-515105195. I think you're hooking right into GroupEditor anyways for GroupCreation, so I'm wondering if we can get rid of GroupCreation entirely and just change the App.js line for it to call GroupEditor with that new parameter like in GroupCreation already.

**Review by hbh7 — APPROVED** [review]
Looks good I believe. I don't necessarily understand it all but that's okay lol

**Comment by hbh7** [comment]
Oh side note, something like updating React would preferably be a separate branch/PR but it's fine for this time I suppose.

**Review by neha-deshpande001 — APPROVED** [review]

**Comment by hbh7** [comment]
One of these days I'll hopefully get better about catching incorrect base branches

**Pull request merged**
