### PR TITLE
Added Dynamic Header Dropdown Menu

### PR DESCRIPTION
**Pull request by jbsandling**
### Description of change(s), including why:

Adjusted the Menu in the header to display Login, Register, and Enter Poll Code when loggedIn in localStorage is false, and Account, Enter Poll Code, Groups, History, Settings, and Logout when loggedIn in localStorage is true. This way the menu will only display ways to log in (as well as the poll code entry) if a user is not logged in, and allow user to access the pages that require them to be logged in if they have logged in. Done in a response to Issue #174.

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- In the issue this is based on (#174), it is also specified that we "Make sure each menu item links to the correct path". All options link to working paths except History and Settings. For History, I just linked it to the same page as in App.js, which is currently an error screen. I was not sure where Settings should go, but due to the age of the issue, I suspect this is no longer used?

### Closing issues:

- Closes #XXXX

### Screenshots (if frontend change) of before and after:
Before:
dynamicHeaderBefore

After (Logged out):
dynamicHeaderAfterLoggedOut

After (Logged in):
dynamicHeaderAfterLoggedIn

### CODE REVIEW

**Review by hbh7 — CHANGES_REQUESTED** [review]
Looking good so far! Just one thing, can you make it so that clicking the logout button also makes a call to `/api/users/logout` to fully complete the process? (see [here](https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Backend-Routes-(Users)#apiuserslogout) for info)
Thanks!

**Comment by jbsandling** [comment]
> Looking good so far! Just one thing, can you make it so that clicking the logout button also makes a call to `/api/users/logout` to fully complete the process? (see [here](https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Backend-Routes-(Users)#apiuserslogout) for info)

My most recent commit includes a get call to the backend logout, however, the specifications also suggest that the frontend should clear its own cache as well, is this referring to the values in localStorage being cleared? 
Thank you!

**Review by hbh7 — CHANGES_REQUESTED** [review]
Looking good! Sorry, one more thing I just thought of, can you wait for a successful response from the call to the backend logout endpoint, and only then clear frontend data? Might as well try to have a bit of consistency between the frontend and backend to hopefully avoid some weird edge cases. Thanks!

**Review by hbh7 — APPROVED** [review]
Looks good! I changed the backend response handler to check our api format's `result` key instead of just `response.ok`. `response.ok` isn't wrong in any way, it just feels slightly better to me to also check the data the backend is returning. I left both as I think it'd throw an error if `!response.ok`, as I think then `response.json()` and `response.result` would fail. :)

**Pull request merged**
