### PR TITLE
Groups functionality

### LINKED ISSUE #268: Groups page functionality
**Please describe what has to be done**

- [x] Should request from the backend what groups the user is a part of. 
- [x] Then, dynamically generate boxes (of equal width) for each group. 
- [x] Display the loading wheel while waiting for data. 
- [x] Display an error if something goes wrong in the loading process. 
- [x] Display a relevant message if a user is part of no groups. 
- [x] Bounce to /login if user is not logged in

### PR DESCRIPTION
**Pull request by neha-deshpande001**
### Description of change(s), including why:

Finished (almost all) the requirements from https://github.com/PollBuddy/PollBuddy/issues/268.

Added state variables for error, loading, and two arrays listing the groups that the user is part of. Currently, all of this is hardcoded, but when the backend api/users/:id/groups functionality works, we can fetch data from there. Using the two arrays, dynamically generates buttons (of equal width) for each group. It checks the length of each array, and if the user is not part of any groups, it displays a message. 

Currently, the loading wheel always appears, and there is a button to stop loading, which we can remove later. If there is an error, it displays a message. There is no functionality for Bounce to /login if user is not logged in

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- Should request from the backend what groups the user is a part of
- Bounce to /login if user is not logged in

### Closing issues:

- Closes #268 

### Screenshots (if frontend change) of before and after:
groups
no member
no admin
loading
error

### CODE REVIEW

**Review by hbh7 — CHANGES_REQUESTED** [review]
I think I'm definitely liking the equal width boxes there. Feels cleaner. 

The spacing though I think could be slightly larger between the Sorry message and the next header, and slightly smaller between the header and first button. 

The error message obviously looks bad but that's a separate issue so no worries there. 

Looks great otherwise though!

**Comment by neha-deshpande001** [comment]
I just fixed the spacing issues that @hbh7 mentioned. Screenshots attached. Additionally, I made the error message centered and inside a box. Eventually, we should probably make an error component and pass in relevant text to display, depending on the error.

edited_spacing2
edited_spacing
edited_spacing3
edited_error

**Comment by hbh7** [comment]
I'm sorry to be so pedantic with this lol but since we're here, can these sections be a little bit smaller? Maybe the size of the box? I promise I won't ask for anything else haha
image

**Comment by neha-deshpande001** [comment]
Hopefully this is better:
image

**Review by hbh7 — APPROVED** [review]
I like it, thanks :)

**Pull request merged**
