### PR TITLE
Fixed leaving groups functionality

### LINKED ISSUE #406: Groups page fixing leaving groups, code cleanup
**Please describe what has to be done**
At some point, the Leave Group button stopped showing Xs. This should be fixed. Also, the methods for leaving/joining groups are very similar/ambiguous and should be made more clear as to what does what.

### PR DESCRIPTION
**Pull request by jssunray34**
### Description of change(s), including why:

On the My Groups page, I fixed the leave groups functionality. When the Leave Group button is clicked, Xs now appear next to each group. When the user clicks on an X, a dialog box opens prompting the user to confirm whether they would like to leave the group.

Additionally, I changed the button text for creating a new group and joining an existing group to make it more clear to the user what these buttons do.

### Type of change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- A backend request will need to be made so that users can actually leave groups.

### Closing issues:

- Closes #406 

### Screenshots (if frontend change) of before and after:
406_before
406_after
406_after_2

### CODE REVIEW

**Review by neha-deshpande001 — CHANGES_REQUESTED** [review]
Overall, this is good. I have a suggestion - how about after the user officially leaves the group by clicking "Yes," it automatically leaves the Exit Leave Group mode? I doubt people would want to leave multiple classes at the same time.

Also, it looks like there are some lint checks (warnings) for camelCase and variables that have been defined but not used, so that should be fixed before merging.

**Comment by jssunray34** [comment]
I changed the color of the Leave Group button to be darker when the user enters Leave Group mode. What do you think? It is subtle, but I think it makes it a little more clear to the user.

**Review by hbh7 — CHANGES_REQUESTED** [review]
Overall I think this looks good! We may tweak the button coloring/styling more eventually but I think it's perfectly fine for now. I also like the other changes you've made like the variable naming and wording changes on the buttons to be more clear. 

The only thing is it'd be great if you could move the page-specific styles into a new `Groups.scss` file next to `Groups.js` and have them all use the `groups_` prefix (I see some have it already which is great) so there's no risk of conflicts when they're merged with other styles (yay React...). Then you just add a `import "./Groups.scss";` to the top of the `Groups.js` file to hook them in. Should be a quick change :) Thanks!

**Review by hbh7 — APPROVED** [review]
Perfect!

**Review by neha-deshpande001 — APPROVED** [review]

**Pull request merged**
