### PR TITLE
fix(backend): format 404 error as a JSON response.

### LINKED ISSUE #628: Backend 404 page should be in our response format
**Please describe what has to be done**
Visiting something like https://pollbuddy.app/api/test (a deleted endpoint) yields "Not Found". It'd be better to wrap it in our "result" and "error" json format.

### PR DESCRIPTION
**Pull request by khirupa**
### Description of change(s), including why:

Added error json response with 404 status code
Removed CreateError function inside next()

### Type of change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- (none)

### Closing issues:

- Closes #628

### CODE REVIEW

**Review by hbh7 — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution. I just want to clarify what I meant in the issue. We have a `createResponse(...)` function in our `utils.js` file in the backend's `modules` folder. I'm looking for that to be used (swap it out with createError, and adapt the arguments). Also, if you could use the error message "API route not found." (I should have specified in the issue, sorry), that'd be great. 

Feel free to make the change, commit, push to the same branch, and the PR will update automatically. Then, I'll take another look. Thanks!

**Comment by hbh7** [comment]
Any updates @khirupa ?

**Comment by khirupa** [comment]
Hi, and I apologize for the delay. I'll get started on this as soon as possible and push it through. Thank you for your feedback.

**Review by hbh7 — APPROVED** [review]
No worries, looks perfect, thanks!

**Review by JaBeast13 — DISMISSED** [review]

**Pull request merged**
