### PR TITLE
Backend Lint Updates

### LINKED ISSUE #574: Backendend lint warnings cleanup
**Please describe what has to be done**
There are a ton of warnings produced by the linter. If we could significantly reduce or zero-out this number, that would be great and make it much easier to see what warnings are relevant to code sections that people are working on.

### PR DESCRIPTION
**Pull request by djwalker200**
### Description of change(s), including why:

I cleaned up the Backend Lint warnings

### Type of change(s)

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

There are a few remaining unused variable warnings referring to functions but I have left these functions in the code to potentially be used later.

### Closing issues:

- Closes #574 
-

### CODE REVIEW

**Review by PrinxeShamar — DISMISSED** [review]

**Review by hbh7 — CHANGES_REQUESTED** [review]
I'm curious as to your thought process with renaming a lot of the variables to have an underscore prefix. To my knowledge, JavaScript doesn't handle variables with that prefix in any special way, and it doesn't seem to have cleared the unused variable warning. A better method for something like req/res/next which we can't do away with (by Express's design) would be to add this line `// eslint-disable-next-line no-unused-vars` before the route definition line. You can actually see a few examples of that in the code already. Unless there's a good reason to keep the underscored names, those should probably be reverted to keep people from getting confused as to why some have it and some don't.

**Comment by PrinxeShamar** [comment]
I believe it was supposed to fix the Github Action Warnings and not the eslint warnings.

**Comment by hbh7** [comment]
The Github Action warnings are the eslint warnings, it's eslint that generates them, so they should be one in the same.

**Review by hbh7 — APPROVED** [review]
Reviewed, edited, and fixed the remaining applicable issues.

**Pull request merged**
