### PR TITLE
689

### LINKED ISSUE #689: (Quick Start) User Guide
**Please describe what has to be done**
A professor has expressed interest in using Poll Buddy in their classes, but we do not have amazing user documentation to refer them to. I'd like to have a user guide for how to use the application as a normal user, or a professor as an example. A quick start guide would be a good supplement as well.

This guide should have information about what the terminology is (groups, polls, questions, etc.), how they can get started on the platform creating groups and polls, and how others can join the group to answer these questions.

### PR DESCRIPTION
**Pull request by alexxie2288**
### Description of change(s), including why:

I added an option to the menu drop list where users can have access to a quick user guide. Specific instructions not implemented yet but should be added bu Curtex02 later.

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- Curtex02 is going to work on the documentation part of this issue

### Closing issues:

- Closes #689 

### Screenshots (if frontend change) of before and after:
image

### CODE REVIEW

**Review by Curtex02 — DISMISSED** [review]

**Review by hbh7 — DISMISSED** [review]
Looks good to me, although I'd probably have picked "/guide" as the URL. Where'd you add it to the header dropdown? Some other general comments would be that ideally you'd PR changes like this to the frontend branch rather than master, and also markdown checkboxes are formed like `- [x] thing`, not like `- [ x ] thing` in order to have Github render them properly.

**Comment by alexxie2288** [comment]
> 

Ok got it, and the quick user guide should be added next to polls/history and logout

**Comment by Curtex02** [comment]
comim1
comim2

**Review by Curtex02 — APPROVED** [review]

**Review by hbh7 — APPROVED** [review]
Looks good!

**Comment by hbh7** [comment]
Oops, I should have switched the branch to frontend first before merging, my bad. It's merged but Github doesn't realize it. :/

**Pull request closed without merging**
