### PR TITLE
Login with school

### LINKED ISSUE #281: Login With School Page functionality
**Please describe what has to be done**

- [x] Populate the schools dropdown with a call from the backend
- [x] Probably use the loading wheel since the only thing you can do on this page is select a school, so you need that to be ready
- [x] Remove the CAS button, send to CAS backend URL if selecting RPI. This should probably be handled by the backend. Ex: Backend call returns an array of schools and URLs to redirect to. This functionality may or may not exist in the backend so an issue may need to be made for that.

### PR DESCRIPTION
**Pull request by lulujoe**
### Description of change(s), including why:
I finished two main functions:
**Populate the schools dropdown with a call from the backend.**
The login-with-school page will call "api/schools" API to get school information and then populate the schools dropdown. To test my functionality, I also modify the app.js file in backend folder. I checked the pull request of "Added /api/schools request #317 " and hardcoded the API as follows:

>  var schools = {
    "Rensselaer Polytechnic Institute": "https: xxxxx",
    "Worcester Polytechnic Institute": "https: xxxxx",
    "Massachusetts Institute of Technology": "https: xxxxx"
  }; 
  res.json(schools);

From my perspective, I think the API should retrieve data from MongoDB Database instead of hardcode. Furthermore, I assume the return value to be a dictionary with schoolName as key and CAS link as value. It is easier for the frontend page working.

**Remove the CAS button, send to CAS backend URL if selecting RPI.** 
Once user selects a certain school and click submit button, the page will jump to the related CAS website automatically. Since I hardcode "api/schools" API and let all three schools' link is RPI CAS system, in this case, no matter which school you choose, you will jump to the RPI CAS system. But as long as the backend API contains correct link, this function should works fine.

### Type of change(s)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Any work to still do or other concerns:

- (none)

### Closing issues:

- Closes #281 

### Screenshots (if frontend change) of before and after:
Screen Shot 2020-11-15 at 11 36 46 AM
Screen Shot 2020-11-15 at 11 36 57 AM
Screen Shot 2020-11-15 at 11 37 07 AM
Screen Shot 2020-11-15 at 11 37 15 AM

### CODE REVIEW

**Comment by neha-deshpande001** [comment]
The /register/school page isn't loading for me, neither on the github action bot's links, nor if I run it locally. I'm not entirely sure what the problem is. The /login/school page seems to be working properly.

Also, the school button comes before the poll buddy button on the register page, and vice versa for the login page. Could you switch the position of the buttons so that they're consistent between the two pages? (just since you're making changes to the relevant pages)

**Review by hbh7 — CHANGES_REQUESTED** [review]
I've got a few thoughts about changes:

- I think it makes more sense to have the school list population in the school picker component itself, so that way implementing the component is even easier, and then there's also less code duplication from login/register. 
- Not sure why the register page isn't working anymore either. Definitely something to look into though. 
- I also agree with Neha's consistency idea. 

And a few general thoughts to address your questions:
- For your question about the backend /api/schools portion, it should be taken care of in #317 like you linked, so we'll probably just use that one at merge time. I think you're right about including the link though as that's probably slightly easier, but we will want to route through the backend first rather than directly through CAS. That can be handled later though. 
- As for hardcoding it vs having it in the database, the issue comes in that we don't currently have/particularly need any database pre-generation. You _can_ run the /api/gendata endpoint if you want, but it was always more for testing than for intended production use. Database pre-generation for something like the schools list would also possibly require more user and developer setup steps. "Hard coding" it here just means having a global list in the backend, and each school authentication module adds to it. This should make adding more schools as easy as possible, although more work is required for that and is in the works. 

Hopefully that clarifies the thought process a bit.

**Comment by lulujoe** [comment]
> The /register/school page isn't loading for me, neither on the github action bot's links, nor if I run it locally. I'm not entirely sure what the problem is. The /login/school page seems to be working properly.
> 
> Also, the school button comes before the poll buddy button on the register page, and vice versa for the login page. Could you switch the position of the buttons so that they're consistent between the two pages? (just since you're making changes to the relevant pages)

Yes, the register/school function doesn't belong to this issue and I haven't finished that yet. The /login/school page should works.

Sure. I will do modify the format to make them matched.

**Comment by lulujoe** [comment]
> I've got a few thoughts about changes:
> 
> * I think it makes more sense to have the school list population in the school picker component itself, so that way implementing the component is even easier, and then there's also less code duplication from login/register.
> * Not sure why the register page isn't working anymore either. Definitely something to look into though.
> * I also agree with Neha's consistency idea.
> 
> And a few general thoughts to address your questions:
> 
> * For your question about the backend /api/schools portion, it should be taken care of in #317 like you linked, so we'll probably just use that one at merge time. I think you're right about including the link though as that's probably slightly easier, but we will want to route through the backend first rather than directly through CAS. That can be handled later though.
> * As for hardcoding it vs having it in the database, the issue comes in that we don't currently have/particularly need any database pre-generation. You _can_ run the /api/gendata endpoint if you want, but it was always more for testing than for intended production use. Database pre-generation for something like the schools list would also possibly require more user and developer setup steps. "Hard coding" it here just means having a global list in the backend, and each school authentication module adds to it. This should make adding more schools as easy as possible, although more work is required for that and is in the works.
> 
> Hopefully that clarifies the thought process a bit.

Sure! It helps a lot.

I have moved the schoolList and schoolLinkDict items to SchoolPicker.js, which takes me some time to fix bug. Especially I didn't know how to get schoolLinkDict item in loginWithSchool.js if I put it in schoolpicker.js. I figure out that I just need to export it in schoolpicker and import it in loginWithSchool.

I will keep working on the register page. (I will pull request after I finish the register part)

**Comment by hbh7** [comment]
Ok sounds good. Let me know when this is all set and I'll review again.

**Comment by lulujoe** [comment]
Sorry for late reply! I just find changing register page is pretty simple. Basically copying code from loginWithSchool is enough. I also change the order of buttons on register default page so they're consistent between the two pages right now.

One follow-up question is: in the future, if a person who register with a school account, do we need to create a poll buddy account in our own database? (I am not sure whether it will have some benefits but seems like most of the apps I use do things like that 😄 )

**Comment by hbh7** [comment]
Great, I'll review as soon as I can. As for your question, yes, logging in with a school will create a database entry. It should be essentially exactly the same as a regular user but with some special handling. See this wiki page for more information https://github.com/PollBuddy/PollBuddy/wiki/Specifications-%E2%80%90-Database-Schema#database-collections-and-fields

**Review by hbh7 — APPROVED** [review]
Looks great! I imagine some merge difficulties will arise but I can work through those.

**Pull request merged**
